# This file is auto-generated by misc/exports_to_py.py
# DO NOT edit this file manually!
# To regenerate this file, run:
#     python misc/exports_to_py.py

# Enum "TieArch"
TIE_ARCH_X64 = 0
TIE_ARCH_ARM64 = 1
TIE_ARCH_JS = 2
TIE_ARCH_CUDA = 3
TIE_ARCH_METAL = 4
TIE_ARCH_OPENGL = 5
TIE_ARCH_DX11 = 6
TIE_ARCH_DX12 = 7
TIE_ARCH_OPENCL = 8
TIE_ARCH_AMDGPU = 9
TIE_ARCH_VULKAN = 10
TIE_ARCH_GLES = 11
TIE_ARCH_UNKNOWN = 0x7FFFFFFF
