# This file is auto-generated by misc/exports_to_py.py
# DO NOT edit this file manually!
# To regenerate this file, run:
#     python misc/exports_to_py.py

# Enum "TieExtension"
TIE_EXTENSION_SPARSE = 0
TIE_EXTENSION_QUANT = 1
TIE_EXTENSION_MESH = 2
TIE_EXTENSION_QUANT_BASIC = 3
TIE_EXTENSION_DATA64 = 4
TIE_EXTENSION_ADSTACK = 5
TIE_EXTENSION_BLS = 6
TIE_EXTENSION_ASSERTION = 7
TIE_EXTENSION_EXTFUNC = 8
TIE_EXTENSION_UNKNOWN = 0x7FFFFFFF
